[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "strique-protopy"
version = "0.3.2"
description = "Python package for Strique AI with generated protobuf classes and binary_pb files"
requires-python = ">=3.7"


[tool.setuptools]
package-dir = {"" = "src"}
packages = ["strique_protopy"]

[tool.setuptools.package-data]
strique_protopy = ["**/*.py", "**/*.binary_pb"]

[tool.pytest.ini_options]
addopts = "--strict-markers"

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310']

[tool.isort]
profile = "black"

[tool.mypy]
python_version = 3.8
warn_unused_configs = true
strict_optional = true
ignore_missing_imports = true
follow_imports = "silent"

[tool.pylint]
max-line-length = 88
disable = ["C0114", "C0115", "C0116"]
