[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "strique-protopy"
version = "0.1.8"
description = "Python package for Strique AI with generated protobuf classes and binary_pb files"
requires-python = ">=3.7"
dependencies = [
    "grpcio",
    "protobuf",
]

[tool.setuptools]

package-dir = {"" = "."}

[tool.setuptools.package-data]
"*" = ["*.py", "*.binary_pb"]