name: Build and Publish to Private PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Extract version from pyproject.toml
      id: extract_version
      run: |
        VERSION=$(grep '^version =' pyproject.toml | sed 's/version = "//' | sed 's/"//')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Display extracted version
      run: echo "Extracted version is ${{ env.VERSION }}"

    - name: Build proto
      run: |
        python setup.py build
   
    - name: Copy pyproject.toml to new dir
      run: |
       cp ./pyproject.toml ./strique_protopy/
    
        
    - name: Package Proto
      run: |
        cd ./strique_protopy
        python -m build
  

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: List DIR
      run: |
        cwd=$(pwd)
        ls -R
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./strique_protopy/dist/strique_protopy-${{env.VERSION}}-py3-none-any.whl
        asset_name: strique_protopy-${{env.VERSION}}
        asset_content_type: application/gzip