name: Update index with release url

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
  
      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<html>' >> index.html
          echo '<head><title>Simple Index</title></head>' >> index.html
          echo '<body>' >> index.html
          echo '<h1>Simple Index</h1>' >> index.html
          echo '<ul>' >> index.html
          for file in $(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r ".assets[].browser_download_url"); do
            echo "  <li><a href=\"${file}\">$(basename ${file})</a></li>" >> index.html
          done
          echo '</ul>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html
  
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m "Update index.html for release ${{ env.VERSION }}"
          git push
