name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools wheel grpcio grpcio-tools protobuf

    - name: Build proto
      run: |
        python setup.py build
    
    - name: Copy pyproject.toml to new dir
      run: |
       cp ./pyproject.toml ./strique_protopy/
        
    - name: Package Proto
      run: |
        cd ./strique_protopy
        python -m build

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m twine upload --repository-url https://api.github.com/repos/${{ github.repository }} dist/*
      if: github.event_name == 'release'
