name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools wheel grpcio grpcio-tools protobuf

    - name: Build proto
      run: |
        python setup.py build
    
    - name: Copy pyproject.toml to new dir
      run: |
       cp ./pyproject.toml ./strique_protopy/
        
    - name: Package Proto
      run: |
        cd ./strique_protopy
        python -m build

    - name: List dist directory
      run: |
        cd ./strique_protopy/dist
        ls -R

    - name: Publish to GitHub Packages
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m twine upload --repository-url https://upload.github.com/${{ github.repository }} ./strique_protopy/dist/* 
    
