name: Build and Publish to Private PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Extract version from pyproject.toml
        id: extract_version
        run: |

          VERSION=$(grep '^version =' pyproject.toml | sed 's/version = "//' | sed 's/"//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Display extracted version
        run: echo "Extracted version is ${{ env.VERSION }}"

      - name: Build proto
        run: |
          python build_proto.py

      - name: Package Proto
        run: |
          python -m build
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: List DIR
        run: |
          cwd=$(pwd)
          ls -R
        
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/strique_protopy-${{env.VERSION}}-py3-none-any.whl
          asset_name: strique_protopy-${{env.VERSION}}-py3-none-any.whl
          asset_content_type: application/gzip

  update-index:
    needs: build-and-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<html>' >> index.html
          echo '<head><title>Simple Index</title></head>' >> index.html
          echo '<body>' >> index.html
          echo '<h1>Simple Index</h1>' >> index.html
          echo '<ul>' >> index.html
          for file in $(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r ".assets[].browser_download_url"); do
            echo "  <li><a href=\"${file}\">$(basename ${file})</a></li>" >> index.html
          done
          echo '</ul>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m "Update index.html for release ${{ env.VERSION }}"
          git push
